spring.application.name=secure-api-demo

spring.datasource.url=jdbc:h2:mem:secure-api-demo
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=pass

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

jwt.secret=a0r7nUYHS0JiMUVyMY5YctOJv9BqmolrEEKvjbHCSce
jwt.expiration=3600000
jwt.header=Authorization
jwt.prefix=Bearer


